<a href="https://colab.research.google.com/github/roymuli/Python-Projects/blob/main/FDI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import warnings
warnings.filterwarnings('ignore')

# Set floatt format
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
# upload data
file_path = '/content/P_Data_Extract_From_World_Development_Indicators (1).xlsx'
df = pd.read_excel(file_path)

In [3]:
# data overview
df.head(5)

,Country Name,Country Code,Series Name,Series Code,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Kenya,KEN,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,1.202208,0.8838,0.627591,1.640837,0.832686,0.468169,-0.005368,0.382594,0.691646,0.47017,0.372245
1,Kenya,KEN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,5.020111,4.967721,4.213517,3.837958,5.647946,5.114159,-0.272766,7.590489,4.859981,5.555873,4.496498
2,Kenya,KEN,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,1450.593382,1489.119598,1517.977961,1542.33774,1596.690459,1645.709618,1609.334141,1698.895783,1747.531988,1808.404791,1853.087855
3,Kenya,KEN,"Employment to population ratio, ages 15-24, to...",SL.EMP.1524.SP.ZS,42.231,42.003,41.78,38.695,35.749,32.929,31.613,31.752,31.32,30.845,30.633
4,Kenya,KEN,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,16.472804,15.128734,13.249745,12.73666,12.541975,11.427996,9.641869,10.769574,12.191969,11.686105,11.136687

In [4]:
# datasize
df.shape

(341, 15)

In [8]:
# Data cleaning and preparation
df.sample(2)

,Country Name,Country Code,Series Name,Series Code,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
102,Mozambique,MOZ,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,32.79,32.57,35.38,41.04,45.53,37.14,32.79,40.35,49.83,45.28,42.73
297,Niger,NER,"Employment to population ratio, ages 15-24, to...",SL.EMP.1524.SP.ZS,61.69,61.48,61.28,61.08,60.88,60.69,60.10,60.46,59.33,59.69,59.46

In [10]:
# rename column names
df = df.rename(columns= {'Country Name' : 'Country Name',
                        'Country Code': 'Country Code',
                        'Series Name' : 'Economic Indicator',
                        'Series Code' : 'Indicator Code' })

In [11]:
df.head(2)

,Country Name,Country Code,Economic Indicator,Indicator Code,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Kenya,KEN,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,1.20,0.88,0.63,1.64,0.83,0.47,-0.01,0.38,0.69,0.47,0.37
1,Kenya,KEN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,5.02,4.97,4.21,3.84,5.65,5.11,-0.27,7.59,4.86,5.56,4.50

In [13]:
#clean years
df.columns = [ re.sub(r"\s*\[YR\d+\]", "", col) if re.search(r"\d{4}\s*\[YR\d+\]", col) else col for col in df.columns]

In [14]:
df.sample(2)

,Country Name,Country Code,Economic Indicator,Indicator Code,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
282,Malawi,MWI,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,539.56,539.61,538.22,544.80,553.53,569.87,559.45,569.97,560.64,556.74,552.50
266,Guinea,GIN,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,-0.84,0.61,18.83,5.59,2.98,0.33,1.25,1.16,3.31,5.87,5.53

In [ ]:
# check missing values